name: CI Pipeline

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  lint_and_build:
    name: Lint & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use specified node version
        uses: actions/setup-node@v2
        with:
          node-version: "16.14.2"

      - name: Install node dependencies
        run: yarn --immutable --immutable-cache --check-cache
        env:
          HUSKY_SKIP_INSTALL: true
          CI: true

      - name: Lint Code Base
        run: yarn lint --max-warnings=0

      - name: Build Web App
        run: yarn build
